create table if not exists public.asteria_contact_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null check (char_length(name) between 1 and 80),
  email_hash text not null check (char_length(email_hash) = 64),
  client_hash text not null check (char_length(client_hash) = 64),
  message_preview text not null check (char_length(message_preview) <= 160),
  request_id text not null,
  app_version text not null,
  source text not null default 'flask'
);

alter table public.asteria_contact_submissions enable row level security;

revoke all on table public.asteria_contact_submissions from anon, authenticated;

create index if not exists idx_asteria_contact_submissions_created_at
  on public.asteria_contact_submissions (created_at desc);

create index if not exists idx_asteria_contact_submissions_email_hash
  on public.asteria_contact_submissions (email_hash);
